project:
  type: website
  title: Multepal
  output-dir: docs

website:
  title: "The Multepal Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: variorum.qmd
        text: Variorum
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

